services:
  mlflow_service:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - mlflow_volume:/opt/mlflow
    command:
      - /bin/sh
      - -c
      - |
        mkdir -p /opt/mlflow
        mlflow server \
          --host "0.0.0.0" \
          --port "5000" \
          --allowed-hosts "*" \
          --backend-store-uri "sqlite:///opt/mlflow/mlflow.db"

  server_service:
    depends_on:
      mlflow_service:
        condition: service_started
    build:
      context: .
      dockerfile: src/server/Dockerfile
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - PYDEVD_DISABLE_FILE_VALIDATION=1
      - MLFLOW_TRACKING_URI=http://mlflow_service:5000
    env_file:
      - path: .env
        required: false
    command: uv run -m debugpy --listen 0.0.0.0:5678 -m fastapi dev src/server/main.py --host 0.0.0.0
    develop:
      watch:
        - path: src/server
          target: /app/src/server
          action: sync
        - path: src/inference
          target: /app/src/inference
          action: sync

  portal_service:
    depends_on:
      server_service:
        condition: service_started
    build:
      context: .
      dockerfile: src/portal/Dockerfile
    ports:
      - "8501:8501"
      - "5679:5679"
    environment:
      - PYDEVD_DISABLE_FILE_VALIDATION=1
    env_file:
      - path: .env
        required: false
    command: uv run -m debugpy --listen 0.0.0.0:5679 -m streamlit run src/portal/main.py --server.address 0.0.0.0
    develop:
      watch:
        - path: src/portal
          target: /app/src/portal
          action: sync

volumes:
  mlflow_volume:
